#
# Hide the "Info" button in the UI (which shows the "credits / info" screen).
#
hideInfoButton: true

#
# Hide the UI which allows manual adjusting of low level model parameters.
#
hideManualControls: true

#
# Skip the start screen
# The start screen is REQUIRED for running ai-jam on a regular browser
# because a click is needed before the sound subsystem works...
# but can be skipped in our kiosk browser which disables that security
# requirement.
#
skipStartScreen: false

#
# For how many bars will the AI listen before responding
#
pianoCallBars: 2
drumCallBars: 2

#
# How many bars long will the AI's response be
#
pianoResponseBars: 2
drumResponseBars: 2

#
# A number between [0,127] to control how random or similar the AIs response is.
#
pianoTemperature: 64
drumTemperature: 64

#
# Whether the metronome can be heard
#
metronomeEnabled: true

#
# Whether the on screen piano can be played with mouse/touch
#
interactiveOnScreenPiano: false

#
# Number of octaves in the on screen piano
#
onScreenPianoOctaveCount: 4

#
# Lowest note in the on screen piano
#

onScreenPianoLowestNote: 48

#
# Pitches used for the on screen drum pad
#

onScreenDrumPitches: [36, 38, 42, 46, 45, 50, 49, 51]